In [1]:
import pandas as pd
student_name=['ram','shyam','seeta','geeta']
marks=[60,70,80,90]
myvar=pd.Series(marks,index=student_name,name='student_result')
print(myvar)

ram      60
shyam    70
seeta    80
geeta    90
Name: student_result, dtype: int64

In [5]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':430,'day4':370}
myvar=pd.Series(calories,name='calories burn per day',index=['day1','day2'])
print(myvar)

day1    400
day2    380
Name: calories burn per day, dtype: int64

In [13]:
import pandas as pd
calories={'day1':400,'day2':380,'day3':480,'day4':370}
myvar=pd.Series(calories,name='calories burn per day')
print(myvar)
print(myvar.size)
print(myvar.dtype)
print(myvar.name)
print(myvar.index)
print(myvar.values)
# myvar.values
myvar.is_unique

day1    400
day2    380
day3    480
day4    370
Name: calories burn per day, dtype: int64
4
int64
calories burn per day
Index(['day1', 'day2', 'day3', 'day4'], dtype='object')
[400 380 480 370]

True

In [19]:
import pandas as pd
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [15]:
print(type(subs))

<class 'pandas.core.frame.DataFrame'>

In [16]:
import pandas as pd
subs=pd.read_csv('subs.csv',squeeze=True)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [17]:
import pandas as pd
subs=pd.read_csv('subs.csv',squeeze=True)
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [25]:
subs.min()

33

In [26]:
subs.max()

396

In [23]:
subs.median()

123.0

In [24]:
subs.sum()

49510

In [27]:
# Subscribers greater than 200
subs[subs>200]

165    225
166    249
167    265
168    306
169    261
170    222
225    224
226    254
227    214
228    236
229    261
230    247
231    207
232    254
233    301
234    233
240    202
246    259
248    213
249    210
252    216
275    228
276    237
277    276
279    290
280    295
281    245
282    241
283    267
284    269
285    211
287    206
288    202
290    236
291    222
292    203
312    230
318    244
324    243
325    227
326    259
330    396
331    312
332    268
333    229
337    221
338    225
339    221
340    202
344    276
345    258
346    219
347    212
351    220
354    204
358    210
359    209
360    231
361    226
Name: Subscribers gained, dtype: int64

In [28]:
subs[subs>200].size

59

In [33]:
# find day(index) when maximum Subscribers gained
subs[subs==subs.max()].index

Int64Index([330], dtype='int64')

In [35]:
import pandas as pd
movies=pd.read_csv('bollywood.csv')
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [36]:
import pandas as pd
movies=pd.read_csv('bollywood.csv',index_col='movie',squeeze=True)
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [37]:
movies.head()
# by default it will give first 5 movie

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [ ]:
movies.head(10)

In [38]:
movies.tail(3)
# it will give last 3 movie name

movie
Saathiya (film)         Vivek Oberoi
Company (film)            Ajay Devgn
Awara Paagal Deewana    Akshay Kumar
Name: lead, dtype: object

In [39]:
movies[0]

'Vicky Kaushal'

In [40]:
movies[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [41]:
movies[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [42]:
movies[[0,1,3,7,9,10]]

movie
Uri: The Surgical Strike          Vicky Kaushal
Battalion 609                       Vicky Ahuja
Why Cheat India                   Emraan Hashmi
Bombairiya                         Radhika Apte
Thackeray (film)            Nawazuddin Siddiqui
Amavas                                Ali Asgar
Name: lead, dtype: object

In [43]:
'Why Cheat India' in movies

True

In [44]:
'Akshay Kumar' in movies.values

True

In [45]:
movies.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [48]:
movies.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [49]:
movies.value_counts(ascending=True)

Sharib Hashmi        1
Ravi Kishan          1
Sagar Bhangade       1
Harish Chabbra       1
Bidita Bag           1
                    ..
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, Length: 566, dtype: int64

In [51]:
# we want lead which work on more than 20 movies
num_movies=movies.value_counts(ascending=True)
num_movies[num_movies>20]

Emraan Hashmi       21
Shah Rukh Khan      22
Sanjay Dutt         26
Salman Khan         31
Ajay Devgn          38
Amitabh Bachchan    45
Akshay Kumar        48
Name: lead, dtype: int64

In [52]:
num_movies>20

Sharib Hashmi       False
Ravi Kishan         False
Sagar Bhangade      False
Harish Chabbra      False
Bidita Bag          False
                    ...
Sanjay Dutt          True
Salman Khan          True
Ajay Devgn           True
Amitabh Bachchan     True
Akshay Kumar         True
Name: lead, Length: 566, dtype: bool

In [53]:
import pandas as pd
marks={"ram":55,"shyam":60,"seeta":65,"geeta":70}
marks_series=pd.Series(marks,name='student_result')
print(marks_series)

ram      55
shyam    60
seeta    65
geeta    70
Name: student_result, dtype: int64

In [54]:
list(marks_series)

[55, 60, 65, 70]

In [55]:
dict(marks_series)

{'ram': 55, 'shyam': 60, 'seeta': 65, 'geeta': 70}

In [56]:
marks_series[1]=100
marks_series

ram       55
shyam    100
seeta     65
geeta     70
Name: student_result, dtype: int64

In [57]:
100+marks_series

ram      155
shyam    200
seeta    165
geeta    170
Name: student_result, dtype: int64

In [58]:
marks_series

ram       55
shyam    100
seeta     65
geeta     70
Name: student_result, dtype: int64

In [59]:
marks_series>=100

ram      False
shyam     True
seeta    False
geeta    False
Name: student_result, dtype: bool

In [60]:
import pandas as pd
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,9])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [61]:
print(a==b)
print(a<b)
print(a>b)

0    False
1    False
2    False
3    False
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool
0    True
1    True
2    True
3    True
4    True
dtype: bool

In [62]:
import pandas as pd
data={'calories':[420,380,400,370],
     'duration':[50,40,45,35]}
df=pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       400        45
3       370        35

In [63]:
import pandas as pd
data={'calories':[420,380,400,370],
     'duration':[50,40,45,35]}
df=pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       400        45
3       370        35

In [64]:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [65]:
print(df.iloc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [66]:
print(df['calories'])

0    420
1    380
2    400
3    370
Name: calories, dtype: int64

In [67]:
print(df.loc[[0,1]])

   calories  duration
0       420        50
1       380        40

In [68]:
import pandas as pd
data={'calories':[420,380,400,370],
     'duration':[50,40,45,35]}
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       400        45
day4       370        35

In [69]:
print(df.loc['day1'])

calories    420
duration     50
Name: day1, dtype: int64

In [70]:
print(df.iloc['day1'])
# for string it is not work iloc always work for integer key

TypeError: Cannot index by location index with a non-integer key

In [71]:
print(df[::2])

      calories  duration
day1       420        50
day3       400        45

In [74]:
print(df.loc[0])

KeyError: 0

In [75]:
import pandas as pd
data={'Name':['Alice','Bob','charlie'],
     'Age':[25,30,35],
     'City':['new York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     new York
1      Bob   30  Los Angeles
2  charlie   35      Chicago

In [76]:
print(df.loc[0:1])

    Name  Age         City
0  Alice   25     new York
1    Bob   30  Los Angeles

In [77]:
print(df.iloc[0:1])

    Name  Age      City
0  Alice   25  new York

In [78]:
df.loc[(df.Age>26)]

      Name  Age         City
1      Bob   30  Los Angeles
2  charlie   35      Chicago

In [79]:
import pandas as pd
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['r1','r2','r3','r4'])
df

    A  B
r1  1  5
r2  2  6
r3  3  7
r4  4  8

In [80]:
df.loc['r2':'r4',"B"]=99
df

    A   B
r1  1   5
r2  2  99
r3  3  99
r4  4  99

In [81]:
df.iloc[1:3,0]=0
df

    A   B
r1  1   5
r2  0  99
r3  0  99
r4  4  99

In [82]:
df['c']=[10,20,30,40]
df

    A   B   c
r1  1   5  10
r2  0  99  20
r3  0  99  30
r4  4  99  40

In [83]:
df.loc[df['A']==0,'New-col']='Zero'
df

    A   B   c New-col
r1  1   5  10     NaN
r2  0  99  20    Zero
r3  0  99  30    Zero
r4  4  99  40     NaN

In [85]:
df.loc[len(df)]=['John',35,50,'Zero']
df

       A   B   c New-col
r1     1   5  10     NaN
r2     0  99  20    Zero
r3     0  99  30    Zero
r4     4  99  40     NaN
4   John  35  50    Zero

In [87]:
import pandas as pd
data={'Name':['Alice','Bob','charlie'],
     'Age':[25,30,35],
     'City':['new York','Los Angeles','Chicago']}
df=pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     new York
1      Bob   30  Los Angeles
2  charlie   35      Chicago

In [88]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [89]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [90]:
df.size

9

In [91]:
df.values

array([['Alice', 25, 'new York'],
       ['Bob', 30, 'Los Angeles'],
       ['charlie', 35, 'Chicago']], dtype=object)

In [92]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [93]:
df.ndim

2

In [94]:
df.shape

(3, 3)